import './globals.css'
import { Montserrat, Fraunces } from 'next/font/google'

const montserrat = Montserrat({
	subsets: ['latin'],
	weight: ['500', '700'],
	variable: '--font-montserrat',
})
const fraunces = Fraunces({
	subsets: ['latin'],
	weight: '700',
	variable: '--font-fraunces',
})

export const metadata = {
	title: 'Product Preview Card',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang='en'>
			<body className={`${montserrat.variable} ${fraunces.variable} bg-cream`}>
				{children}
			</body>
		</html>
	)
}
